version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: kikr_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - kikr
  kikr:
    build:
      context: .
      dockerfile: Dockerfile
    image: sebhoss/kikr:latest
    environment:
      PORT: 8080
      DB_NAME: kikr_dev
      DB_USER: postgres
      DB_PASS: postgres
      DB_HOST: postgres
    depends_on:
      - postgres
    ports:
      - "50123:8080"
    networks:
      - kikr

networks:
  kikr:
    driver: bridge
